version: '3.9'

services:

  db:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

env_file:
  - .env